services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: soumyadevopsspace/catalogue:1.0.0
    container_name: catalogue
    depends_on: 
    - mongodb
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile # It moves to mongodb directory
    image: soumyadevopsspace/mongodb:1.0.0 # docker build -t soumyadevopsspace/mongodb:1.0.0
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually